#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"          # absolute, so the wizard runs from anywhere
PROBE_DIR="$ROOT/data/attio-probes"

banner "Attio workspace + importer probes — issue #12"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — checking this machine"
say "No browser work yet. Checking Node before we touch Attio."
printf '\n'

if ! command -v node >/dev/null 2>&1; then
  warn "node is not installed. Install Node 20+ and re-run."
  exit 1
fi
if ! node -e 'process.exit(process.versions.node.split(".")[0] >= 20 ? 0 : 1)'; then
  warn "node 20+ required (found $(node -v)) — the prober uses global fetch."
  exit 1
fi
note "node $(node -v)"
printf '\n'
say "What this wizard gets us, and why it cannot be automated:"
note "  Attio has no CSV import endpoint (issue #2) — import is UI-only. So the"
note "  three imports in stages 5-6 need your clicks. Everything either side of"
note "  them is scripted: the wizard enumerates the schema, generates the probe"
note "  files from your workspace's real option labels, and reads back the result."
printf '\n'
pause "Press Enter to start on Attio."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Attio — create a free workspace"
say "The Free plan is \$0: 3 seats, 50,000 records, 3 objects, API included."
say "No card is needed and nothing here costs money."
printf '\n'
open_url "https://app.attio.com/welcome/sign-up"
printf '\n'
step "Sign up (Google or email — either is fine)."
step "When asked for a workspace name, 'notion2attio' keeps things obvious."
step "Skip every optional onboarding step you can: no teammates to invite,"
step "  no email/calendar sync, no data import yet."
printf '\n'
warn "Do NOT connect your real email or calendar. Attio would ingest your"
warn "contacts and fill Companies and People with noise, which would make the"
warn "probe rows in stage 5 much harder to read."
printf '\n'
note "If you already have an Attio workspace you are happy to scribble in, use"
note "that instead — the probes only add a handful of clearly-named companies,"
note "and stage 7 deletes them again."
printf '\n'
pause "Workspace ready?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Attio — enable the Deals object"
say "Our emitter writes two files: people.csv and deals.csv (issue #2). Deals"
say "is a standard object but is not always switched on in a new workspace."
printf '\n'
open_url "https://app.attio.com/_/settings/data/objects"
printf '\n'
step "Find 'Deals' in the object list."
step "If it is off, switch it on. Companies and People are on by default."
printf '\n'
note "The Free plan caps you at 3 objects — Companies, People and Deals is"
note "exactly 3, so do not add a custom object as well."
printf '\n'
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Attio — create an API key"
say "The key lets the prober read the schema and check what your imports"
say "actually landed. It never imports anything — Attio has no such endpoint."
printf '\n'
open_url "https://app.attio.com/_/settings/developers"
printf '\n'
step "Click 'Create an integration' (or open an existing one)."
step "Name it notion2attio-probe."
step "Open its 'Access token' / 'API key' tab and grant these scopes:"
printf '\n'
say "    object_configuration:read      read objects, attributes, select options"
say "    record_permission:read-write   read back imported rows, and try one write"
printf '\n'
step "Generate the token and copy it."
printf '\n'
warn "Attio shows the token once. Copy it before leaving that screen."
note "Input below is hidden — nothing appears on screen."
printf '\n'
ask_secret ATTIO_API_KEY "Paste the API key:"
if [[ -z "$ATTIO_API_KEY" ]]; then
  warn "no key entered — re-run when you have it."
  exit 1
fi
write_env ATTIO_API_KEY "$ATTIO_API_KEY"
note "$ENV_FILE is gitignored; the key stays on this machine."
printf '\n'
pause "Press Enter to enumerate the workspace."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Enumerate the schema, then build the probe files"
say "This is the part the docs cannot tell us: the real option labels of"
say "Companies' Employee range, which Attio does not publish and which cannot"
say "be edited because it is a system enriched attribute."
printf '\n'

if ! node "$ROOT/scripts/probe-attio.mjs" schema; then
  printf '\n'
  warn "schema enumeration failed. A 403 means the key is missing a scope —"
  warn "go back to stage 4 and check both scopes are granted."
  exit 1
fi
printf '\n'
pause "Read the Employee range labels above, then press Enter."

printf '\n'
if ! node "$ROOT/scripts/probe-attio.mjs" csv; then
  printf '\n'
  warn "could not generate the probe CSVs."
  exit 1
fi
printf '\n'
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Import the three probe files by hand"
say "Three imports into Companies. Each takes about a minute. They differ only"
say "in bytes — encoding, BOM, line endings, delimiter — which is the whole"
say "point: the docs never state what Attio accepts."
printf '\n'
note "Files are in: data/attio-probes/"
note "  probe-a-utf8-lf-comma.csv        UTF-8, no BOM, LF, comma  (our intended emit)"
note "  probe-b-utf8bom-crlf-comma.csv   UTF-8 WITH BOM, CRLF      (what Excel produces)"
note "  probe-c-utf8-lf-semicolon.csv    semicolon-delimited       (European Excel)"
printf '\n'
open_url "https://app.attio.com/_/imports"
printf '\n'
step "Start an import, choose Companies, upload probe-a first."
step "At the mapping step, map all four columns BY HAND:"
say "      Domains → Domains,  Name → Name,"
say "      Employee range → Employee range,  Description → Description"
step "At the review step, do NOT tick 'Create missing select options'."
say "      We want to see what matches on its own — creating options would"
say "      erase the answer we came for."
step "Note anything Attio complains about, then run the import."
step "Repeat for probe-b, then probe-c. One at a time."
printf '\n'
warn "Run them one at a time. Attio's own troubleshooting page says concurrent"
warn "imports can get stuck and fail to progress."
printf '\n'
note "If a file is rejected outright — probe-c very well might be — that IS the"
note "result. Write down what the error said and move on to the next file."
printf '\n'
pause "All three imports finished (or refused)?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Read back what actually landed"
say "Now the API tells us the truth about those bytes, with every non-ASCII"
say "character printed as its codepoint — the dash question is invisible"
say "otherwise."
printf '\n'

node "$ROOT/scripts/probe-attio.mjs" readback || warn "readback failed"
printf '\n'
pause "Press Enter to try the direct API write to the enriched select."

printf '\n'
node "$ROOT/scripts/probe-attio.mjs" write || warn "write probe failed"
printf '\n'

say "Two things left, both optional and both later:"
note "  - Re-run 'node scripts/probe-attio.mjs readback' in a few hours. If"
note "    stripe.com's Employee range has changed, enrichment overwrites us."
note "  - 'node scripts/probe-attio.mjs cleanup' deletes the probe companies."
printf '\n'
SKIPPED+=("paste the stage 5-7 output into issue #12 as the resolution")

finish
