#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"          # absolute, so the wizard runs from anywhere
REPO="Qiuyi-Hong/notion2attioBackend"
NOTION_VERSION="2026-03-11"

banner "Notion source database — issue #5"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — checking this machine"
say "No browser work yet. Checking Node and the row fixture before Notion."
printf '\n'

if ! command -v node >/dev/null 2>&1; then
  warn "node is not installed. Install Node 20+ and re-run."
  exit 1
fi
if ! node -e 'process.exit(process.versions.node.split(".")[0] >= 20 ? 0 : 1)'; then
  warn "node 20+ required (found $(node -v)) — the seeder uses global fetch."
  exit 1
fi
note "node $(node -v)"
printf '\n'

if ! node "$ROOT/scripts/check-notion-fixture.mjs"; then
  printf '\n'
  warn "the row fixture is wrong. Fix it before seeding anything."
  exit 1
fi
printf '\n'
pause "Fixture is good. Press Enter to start on Notion."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Notion — create an integration"
say "Notion will not talk to the API until an 'internal integration' exists."
printf '\n'
open_url "https://www.notion.so/profile/integrations"
printf '\n'
step "Click 'New integration'."
step "Name it anything — notion2attio-dev is fine."
step "Associated workspace: the workspace you want the demo database in."
step "Type: Internal."
step "Under Capabilities tick: Read content, Update content, Insert content."
step "Save, open the integration, and reveal its Internal Integration Secret."
printf '\n'
note "The secret starts with ntn_ (older integrations start with secret_)."
note "Input is hidden — nothing you type here appears on screen."
printf '\n'
ask_secret NOTION_TOKEN "Paste the integration secret:"
if [[ -z "$NOTION_TOKEN" ]]; then
  warn "no token entered — re-run when you have it."
  exit 1
fi
write_env NOTION_TOKEN "$NOTION_TOKEN"
note "$ENV_FILE is gitignored; the secret stays on this machine."
printf '\n'
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Notion — create a parent page and share it"
say "The database is created inside a page you own, and the integration can"
say "only see pages you have explicitly shared with it."
printf '\n'
open_url "https://www.notion.so/"
printf '\n'
step "Create a new, empty page — 'notion2attio demo' is fine."
step "On that page: ••• menu (top right) → Connections."
step "Pick the integration you created in the last stage."
step "Copy the page URL from the address bar."
printf '\n'
warn "Skip the Connections step and the API returns 404, not a permission error —"
note "  Notion hides unshared pages from an integration entirely."
printf '\n'
ask NOTION_PARENT_PAGE_ID "Paste the page URL (or just its id):"

# Pull the last run of 32 hex characters out of whatever was pasted, then
# hyphenate it into a uuid. Idempotent, so a saved id survives a re-run.
RAW_ID="$(printf '%s' "$NOTION_PARENT_PAGE_ID" | tr -d '\n-' | grep -oE '[0-9a-fA-F]{32}' | tail -n1 || true)"
if [[ -z "$RAW_ID" ]]; then
  printf '\n'
  warn "couldn't find a 32-character page id in that."
  note "A Notion page URL ends in 32 hex characters, e.g."
  note "  https://www.notion.so/My-Page-1f2e3d4c5b6a79880123456789abcdef"
  exit 1
fi
NOTION_PARENT_PAGE_ID="${RAW_ID:0:8}-${RAW_ID:8:4}-${RAW_ID:12:4}-${RAW_ID:16:4}-${RAW_ID:20:12}"
write_env NOTION_PARENT_PAGE_ID "$NOTION_PARENT_PAGE_ID"
printf '\n'
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Checking the token can actually see that page"
say "Probing the Notion API before anything is written to your workspace."
printf '\n'
PROBE="$(mktemp)"
HTTP_STATUS="$(curl -sS -o "$PROBE" -w '%{http_code}' \
  -H "Authorization: Bearer $NOTION_TOKEN" \
  -H "Notion-Version: $NOTION_VERSION" \
  "https://api.notion.com/v1/pages/$NOTION_PARENT_PAGE_ID" 2>/dev/null || echo 000)"

case "$HTTP_STATUS" in
  200)
    note "200 OK — the integration can read the parent page."
    rm -f "$PROBE"
    ;;
  401)
    warn "401 — Notion rejected the token."
    note "Re-run and re-copy the Internal Integration Secret (stage 2)."
    rm -f "$PROBE"
    exit 1
    ;;
  404)
    warn "404 — the integration cannot see that page."
    note "Almost always the ••• → Connections step in stage 3."
    note "Also 404 if the page lives in a different workspace than the one"
    note "the integration was associated with."
    rm -f "$PROBE"
    exit 1
    ;;
  000)
    warn "could not reach api.notion.com — check your network."
    rm -f "$PROBE"
    exit 1
    ;;
  *)
    warn "unexpected HTTP $HTTP_STATUS from Notion:"
    cat "$PROBE"
    rm -f "$PROBE"
    exit 1
    ;;
esac
printf '\n'
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the database and seed 12 rows"
say "This is the first thing that writes to your Notion workspace:"
say "one 'Qualified accounts' database, 18 properties, 12 rows."
printf '\n'
note "8 rows match the W34 filter; 4 exist so the filter is provably working."
note "The seeder runs that filter afterwards and fails unless it returns 8."
printf '\n'
warn "Not idempotent — running it twice creates a SECOND database."
printf '\n'
if ! confirm "Create the database now?"; then
  printf '\n'
  note "Nothing was written. Your values are saved in $ENV_FILE, so"
  note "re-running this wizard will skip straight past the prompts."
  exit 0
fi
printf '\n'

SEED_LOG="$(mktemp)"
if ! NOTION_TOKEN="$NOTION_TOKEN" NOTION_PARENT_PAGE_ID="$NOTION_PARENT_PAGE_ID" \
     node "$ROOT/scripts/seed-notion-source-db.mjs" 2>&1 | tee "$SEED_LOG"; then
  printf '\n'
  warn "seeding failed — the error from Notion is above."
  note "If a partial database was created, delete it in Notion before retrying."
  rm -f "$SEED_LOG"
  exit 1
fi

NOTION_DATABASE_ID="$(grep -E '^NOTION_DATABASE_ID=' "$SEED_LOG" | tail -n1 | cut -d= -f2- || true)"
NOTION_DATA_SOURCE_ID="$(grep -E '^NOTION_DATA_SOURCE_ID=' "$SEED_LOG" | tail -n1 | cut -d= -f2- || true)"
rm -f "$SEED_LOG"

if [[ -z "$NOTION_DATABASE_ID" || -z "$NOTION_DATA_SOURCE_ID" ]]; then
  warn "the seeder finished but did not report both ids — check $ENV_FILE."
  exit 1
fi
printf '\n'
write_env NOTION_DATABASE_ID "$NOTION_DATABASE_ID"
write_env NOTION_DATA_SOURCE_ID "$NOTION_DATA_SOURCE_ID"
printf '\n'
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Record the ids on issue #5"
say "The ticket's last unmet requirement is the database id on the record."
printf '\n'
note "database id     $NOTION_DATABASE_ID"
note "data source id  $NOTION_DATA_SOURCE_ID"
printf '\n'

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Post both ids as a comment on #5?"; then
    COMMENT="$(mktemp)"
    {
      printf '## Database stood up\n\n'
      printf 'Seeded by `scripts/notion-setup-wizard.sh`. The seeder ran the W34\n'
      printf 'extraction filter against the live data source and it returned exactly\n'
      printf 'the 8 expected rows out of 12.\n\n'
      printf '```\n'
      printf 'NOTION_DATABASE_ID=%s\n' "$NOTION_DATABASE_ID"
      printf 'NOTION_DATA_SOURCE_ID=%s\n' "$NOTION_DATA_SOURCE_ID"
      printf '```\n\n'
      printf 'Queries go to the **data source**, not the database:\n'
      printf '`POST /v1/data_sources/%s/query`\n' "$NOTION_DATA_SOURCE_ID"
    } > "$COMMENT"
    if gh issue comment 5 --repo "$REPO" --body-file "$COMMENT" >/dev/null 2>&1; then
      printf '  %s✓ commented%s on %s#5\n' "$GREEN" "$RESET" "$REPO"
    else
      SKIPPED+=("comment the ids on $REPO#5")
      warn "couldn't comment on #5 — post the ids by hand."
    fi
    rm -f "$COMMENT"
  else
    SKIPPED+=("comment the ids on $REPO#5")
  fi
else
  SKIPPED+=("comment the ids on $REPO#5 (gh not ready)")
  warn "gh unavailable — post the ids on #5 by hand."
fi

# Deliberately does NOT close #5: closing a wayfinder ticket also means writing
# its resolution into the map (#1) Decisions-so-far. That is left to the agent.
SKIPPED+=("close #5 and update the map (#1) — ask Claude to finish the ticket")

printf '\n'
pause "Press Enter for the summary."

finish

printf '  %sThe database%s\n' "$BOLD" "$RESET"
note "  https://www.notion.so/$(printf '%s' "$NOTION_DATABASE_ID" | tr -d '-')"
printf '\n'
printf '  %sNext%s\n' "$BOLD" "$RESET"
note "  Tell Claude \"the database is up\" — it will close #5 and update the map."
printf '\n'
